# Generated by Django 6.0.4 on 2026-06-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_rating_review_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
    ]
